include ../shared.mk

# 1. Grab all .c files here, AND explicitly pull the sensor file from the sibling folder
SOURCES := $(wildcard *.c) ../distance_sensor/vl53l0x.c

CFLAGS += -Werror

include ../end.mk